import Foundation
import Observation
import UserNotifications
import SwiftData
import os

private let logger = Logger(subsystem: "com.blackbookdevelopment.app", category: "Reminders")

/// Manages contact reminders and local notification scheduling.
@Observable
final class ReminderService {
    var notificationsAuthorized = false

    /// Requests notification permission from the user.
    func requestNotificationPermission() async {
        do {
            notificationsAuthorized = try await UNUserNotificationCenter.current()
                .requestAuthorization(options: [.alert, .badge, .sound])
        } catch {
            logger.warning("Notification permission request failed: \(error.localizedDescription)")
            notificationsAuthorized = false
        }
    }

    func scheduleNotification(for reminder: Reminder) {
        guard notificationsAuthorized else { return }
        let content = UNMutableNotificationContent()
        content.title = "Blackbook Reminder"
        content.body = reminder.title
        if let contact = reminder.contact { content.subtitle = contact.displayName }
        content.sound = .default
        content.userInfo = [
            "reminderId": reminder.id.uuidString,
            "contactId": reminder.contact?.id.uuidString ?? ""
        ]
        let comps = Calendar.current.dateComponents([.year, .month, .day, .hour, .minute], from: reminder.dueDate)
        let trigger = UNCalendarNotificationTrigger(dateMatching: comps, repeats: false)
        UNUserNotificationCenter.current().add(
            UNNotificationRequest(identifier: reminder.id.uuidString, content: content, trigger: trigger)
        )
    }

    func cancelNotification(for reminder: Reminder) {
        UNUserNotificationCenter.current().removePendingNotificationRequests(withIdentifiers: [reminder.id.uuidString])
    }

    func generateAutoReminders(context: ModelContext) {
        let threshold = AppConstants.Defaults.autoReminderThreshold
        do {
            let descriptor = FetchDescriptor<Contact>(
                predicate: #Predicate { $0.relationshipScore < threshold && $0.relationshipScore > 0 }
            )
            for contact in try context.fetch(descriptor) {
                let hasActive = contact.reminders.contains { !$0.isCompleted && $0.isAutoGenerated }
                guard !hasActive else { continue }
                let reminder = Reminder(
                    contact: contact,
                    title: "Reconnect with \(contact.displayName)",
                    dueDate: Calendar.current.date(byAdding: .day, value: 2, to: Date()) ?? Date(),
                    isAutoGenerated: true
                )
                context.insert(reminder)
                scheduleNotification(for: reminder)
            }
            try context.save()
        } catch {
            logger.error("Failed to generate auto-reminders: \(error.localizedDescription)")
        }
    }
}
