import Foundation
import SwiftData

/// A scheduled reminder associated with a contact, supporting optional recurrence.
@Model
final class Reminder {
    var id: UUID
    var contact: Contact?
    var title: String
    var dueDate: Date
    var isCompleted: Bool
    var recurrence: Recurrence?
    var isAutoGenerated: Bool
    var createdAt: Date

    var updatedAt: Date
    var syncStatus: String = SyncStatus.pending.rawValue
    var lastSyncedAt: Date?

    /// True when the reminder is incomplete and its due date has passed.
    var isOverdue: Bool {
        !isCompleted && dueDate < Date()
    }

    /// Creates a new incomplete reminder for the given contact.
    init(
        contact: Contact,
        title: String,
        dueDate: Date,
        recurrence: Recurrence? = nil,
        isAutoGenerated: Bool = false
    ) {
        self.id = UUID()
        self.contact = contact
        self.title = title
        self.dueDate = dueDate
        self.isCompleted = false
        self.recurrence = recurrence
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = Date()
        self.updatedAt = Date()
    }

    /// Computes the next due date based on the recurrence interval, or nil if non-recurring.
    func nextOccurrence() -> Date? {
        guard let recurrence else { return nil }
        let calendar = Calendar.current
        switch recurrence {
        case .weekly:
            return calendar.date(byAdding: .weekOfYear, value: 1, to: dueDate)
        case .biweekly:
            return calendar.date(byAdding: .weekOfYear, value: 2, to: dueDate)
        case .monthly:
            return calendar.date(byAdding: .month, value: 1, to: dueDate)
        case .quarterly:
            return calendar.date(byAdding: .month, value: 3, to: dueDate)
        }
    }
}

/// Supported repeat intervals for reminders.
enum Recurrence: String, Codable, CaseIterable, Identifiable {
    case weekly = "Weekly"
    case biweekly = "Biweekly"
    case monthly = "Monthly"
    case quarterly = "Quarterly"

    var id: String { rawValue }
}
