import XCTest
import SwiftData
@testable import Blackbook

final class ReminderServiceTests: XCTestCase {

    private var service: ReminderService!

    private func makeContainer() throws -> ModelContainer {
        let schema = Schema([Contact.self, Interaction.self, Note.self, Tag.self, Group.self, Location.self, ContactRelationship.self, Reminder.self, Activity.self, RejectedCalendarEvent.self])
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        return try ModelContainer(for: schema, configurations: [config])
    }

    override func setUp() {
        super.setUp()
        service = ReminderService()
        // Notifications won't be authorized in test, but we can still test
        // the data logic by calling generateAutoReminders and checking the
        // model context for created reminders.
    }

    override func tearDown() {
        service = nil
        super.tearDown()
    }

    func testAutoReminderCreatedForLowScoreContact() throws {
        let container = try makeContainer()
        let context = ModelContext(container)

        let contact = Contact(firstName: "Low", lastName: "Score")
        contact.relationshipScore = 15.0 // Below threshold of 25, above 0
        context.insert(contact)
        try context.save()

        service.generateAutoReminders(context: context)

        // The contact should now have a reminder
        let descriptor = FetchDescriptor<Reminder>()
        let reminders = try context.fetch(descriptor)

        XCTAssertEqual(reminders.count, 1)
        XCTAssertTrue(reminders.first?.isAutoGenerated ?? false)
        XCTAssertTrue(reminders.first?.title.contains("Reconnect") ?? false)
    }

    func testAutoReminderNotCreatedForHighScoreContact() throws {
        let container = try makeContainer()
        let context = ModelContext(container)

        let contact = Contact(firstName: "High", lastName: "Score")
        contact.relationshipScore = 80.0 // Above threshold of 25
        context.insert(contact)
        try context.save()

        service.generateAutoReminders(context: context)

        let descriptor = FetchDescriptor<Reminder>()
        let reminders = try context.fetch(descriptor)

        XCTAssertEqual(reminders.count, 0)
    }

    func testAutoReminderNotDuplicatedIfActiveExists() throws {
        let container = try makeContainer()
        let context = ModelContext(container)

        let contact = Contact(firstName: "Low", lastName: "Score")
        contact.relationshipScore = 15.0
        context.insert(contact)

        // Create an existing active auto-generated reminder
        let existingReminder = Reminder(
            contact: contact,
            title: "Reconnect with Low Score",
            dueDate: Date(timeIntervalSinceNow: 86400),
            isAutoGenerated: true
        )
        context.insert(existingReminder)
        try context.save()

        service.generateAutoReminders(context: context)

        let descriptor = FetchDescriptor<Reminder>()
        let reminders = try context.fetch(descriptor)

        // Should still only have the one existing reminder, not a duplicate
        XCTAssertEqual(reminders.count, 1)
    }
}
