import Foundation
import SwiftData
@testable import Blackbook

/// Shared test utilities for creating in-memory SwiftData containers and test fixtures.
enum TestHelpers {

    /// Creates an in-memory ModelContainer with the full Blackbook schema.
    ///
    /// Use this in tests that need to instantiate @Model objects (Contact, Interaction, etc.).
    /// The container is ephemeral and discarded after the test.
    static func makeContainer() throws -> ModelContainer {
        let schema = Schema([
            Contact.self,
            Interaction.self,
            Note.self,
            Tag.self,
            Group.self,
            Location.self,
            ContactRelationship.self,
            Reminder.self,
            Activity.self,
            RejectedCalendarEvent.self
        ])
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        return try ModelContainer(for: schema, configurations: [config])
    }

    /// Creates a test contact with sensible defaults inserted into the given context.
    @discardableResult
    @MainActor
    static func makeContact(
        firstName: String = "Test",
        lastName: String = "User",
        score: Double = 50,
        isPriority: Bool = false,
        isHidden: Bool = false,
        in context: ModelContext
    ) -> Contact {
        let contact = Contact(firstName: firstName, lastName: lastName)
        contact.relationshipScore = score
        contact.isPriority = isPriority
        contact.isHidden = isHidden
        context.insert(contact)
        return contact
    }

    /// Creates a test interaction attached to the given contact.
    @discardableResult
    @MainActor
    static func makeInteraction(
        contact: Contact,
        type: InteractionType = .call,
        date: Date = Date(),
        sentiment: Sentiment? = .neutral,
        in context: ModelContext
    ) -> Interaction {
        let interaction = Interaction(contact: contact, type: type, date: date, sentiment: sentiment)
        context.insert(interaction)
        contact.lastInteractionDate = max(contact.lastInteractionDate ?? .distantPast, date)
        return interaction
    }

    /// Creates a test note attached to the given contact.
    @discardableResult
    @MainActor
    static func makeNote(
        contact: Contact,
        content: String = "Test note",
        category: NoteCategory? = .general,
        in context: ModelContext
    ) -> Note {
        let note = Note(contact: contact, content: content, category: category)
        context.insert(note)
        return note
    }

    /// Creates a test reminder attached to the given contact.
    @discardableResult
    @MainActor
    static func makeReminder(
        contact: Contact,
        title: String = "Test reminder",
        dueDate: Date = Date(),
        recurrence: Recurrence? = nil,
        isAutoGenerated: Bool = false,
        in context: ModelContext
    ) -> Reminder {
        let reminder = Reminder(contact: contact, title: title, dueDate: dueDate, recurrence: recurrence, isAutoGenerated: isAutoGenerated)
        context.insert(reminder)
        return reminder
    }
}
